import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Thief Detector",
  description: "Generated by creating object detection",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <footer style={{ textAlign: "center", padding: "10px", backgroundColor: "#f4f4f4", color: "black" }}>
         CopyRight  &copy; {new Date().getFullYear()} Payal Kumari, All Rights Reserved.
        </footer>
      </body>
    </html>
  );
}
